In [40]:
import numpy as np

In [41]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx*(1-sx)

In [101]:
X = np.array([[0, 0, 1, 1], 
              [0, 1, 0, 1]])
Y = np.array([[0],
             [1],
             [1],
             [0]])
m = X.shape[1]
print(X)
print(Y)

[[0 0 1 1]
 [0 1 0 1]]
[[0]
 [1]
 [1]
 [0]]


In [102]:
layers_size = [2, 2, 1]
L = len(layers_size)-1
W = dict()
b = dict()
np.random.seed(1)
for i in range(1, L+1):
    W[str(i)] = np.random.randn(layers_size[i], layers_size[i-1])
    b[str(i)] = np.random.randn(layers_size[i], 1)
    assert(W[str(i)].shape == (layers_size[i], layers_size[i-1]))

print(W)
print(b)

{'2': array([[ 1.74481176, -0.7612069 ]]), '1': array([[ 1.62434536, -0.61175641],
       [-0.52817175, -1.07296862]])}
{'2': array([[ 0.3190391]]), '1': array([[ 0.86540763],
       [-2.3015387 ]])}


In [ ]:
Z = dict()
A = dict()
learning_rate = 0.01

for i in range(10000000):
    
    #Forward Propagation
    A['0'] = X
    for j in range(1,L+1):
        Z[str(j)] = np.dot(W[str(j)], A[str(j-1)]) + b[str(j)]
        A[str(j)] = sigmoid(Z[str(j)])
        assert(A[str(j)].shape == (layers_size[j], m))
    
    cost = (-1/m)*np.sum((np.log(A[str(L)])*Y.T)+(np.log(1-A[str(L)])*(1-Y.T)))
    
    if i % 10000 == 0:
        print("Cost after "+str(i)+" iterations is "+str(cost))
    
    #Back Propagation
    dZ = dict()
    dW = dict()
    db = dict()
    
    for j in reversed(range(1, L+1)):
        if j == L:
            dZ[str(j)] = A[str(j)]-Y.T
        else:
            dZ[str(j)] = np.dot(W[str(j+1)].T, dZ[str(j+1)])*sigmoid_derivative(Z[str(j)])
        
        dW[str(j)] = (1/m)*np.dot(dZ[str(j)], A[str(j-1)].T)
        db[str(j)] = (1/m)*np.sum(dZ[str(j)], axis=1, keepdims=True)
        
        assert(dW[str(j)].shape == W[str(j)].shape)
        
        W[str(j)] = W[str(j)] - learning_rate*dW[str(j)]
        b[str(j)] = b[str(j)] - learning_rate*db[str(j)]
    
print(A[str(L)])
    

Cost after 0 iterations is 0.629458958292
Cost after 10000 iterations is 0.47738793354
Cost after 20000 iterations is 0.477387933078
Cost after 30000 iterations is 0.477387932617
Cost after 40000 iterations is 0.477387932157
Cost after 50000 iterations is 0.477387931696
Cost after 60000 iterations is 0.477387931236
Cost after 70000 iterations is 0.477387930776
Cost after 80000 iterations is 0.477387930316
Cost after 90000 iterations is 0.477387929856
Cost after 100000 iterations is 0.477387929397
Cost after 110000 iterations is 0.477387928938
Cost after 120000 iterations is 0.477387928479
Cost after 130000 iterations is 0.477387928021
Cost after 140000 iterations is 0.477387927562
Cost after 150000 iterations is 0.477387927104
Cost after 160000 iterations is 0.477387926646
Cost after 170000 iterations is 0.477387926189
Cost after 180000 iterations is 0.477387925731
Cost after 190000 iterations is 0.477387925274
Cost after 200000 iterations is 0.477387924817
Cost after 210000 iterations

[[ 0.81423284  0.78181958  0.86850498  0.86025294]]
1.00957392485
[[ 0.00081051  0.66620389  0.66620411  0.6668029 ]]
0.478037653436
[[  3.82580146e-04   6.66445350e-01   6.66445409e-01   6.66729474e-01]]
0.477694392667
[[  2.48545827e-04   6.66522121e-01   6.66522149e-01   6.66706241e-01]]
0.477585863188
[[  1.83413731e-04   6.66559689e-01   6.66559706e-01   6.66695060e-01]]
0.477533013088
[[  1.45010995e-04   6.66581932e-01   6.66581944e-01   6.66688562e-01]]
0.477501853922


KeyboardInterrupt: 