In [1]:
import numpy as np

In [38]:
X = [[0,0,1,1],[0,1,0,1]]
y = [[0, 1, 1, 1]]
m = len(X[0])
input_layer_size = 2
hidden_layer_size = 2
output_layer_size = 1
X = np.matrix(X)
y = np.matrix(y)
w1 = np.random.randn(hidden_layer_size, input_layer_size)
b1 = np.random.randn(hidden_layer_size,1)
w2 = np.random.randn(output_layer_size, hidden_layer_size)
b2 = np.random.randn(output_layer_size,1)
for i in range(100000):
    # Forward Propagation
    z1 = np.dot(w1,X)+b1
    a1 = 1/(1+np.exp(-z1))
    z2 = np.dot(w2,a1)+b2
    a2 = 1/(1+np.exp(-z2))
    
    #Cost Calculation
    J = (-1/m)*np.sum(np.multiply(np.log(a2),y) + np.multiply(np.log(1-a2),(1-y)))
    if(i%10000==0):
        print(a2)
        print(J)
    
    # Backward Propagation
    dz2 = a2-y
    dw2 = (1/m)*(np.dot(dz2, a1.T))
    db2 = (1/m)*np.sum(dz2, axis=1)
    gz1 = 1/(1+np.exp(-z1))
    dz1 = np.multiply(np.dot(w2.T, dz2), np.multiply(gz1,1-gz1))
    dw1 = (1/m)*(np.dot(dz1, X.T))
    db1 = (1/m)*np.sum(dz1, axis=1)
    w1 = w1 - 0.01*dw1
    w2 = w2 - 0.01*dw2
    b1 = b1 - 0.01*db1
    b2 = b2 - 0.01*db2
    

[[0.39159408 0.36630122 0.35265668 0.33800263]]
0.9070435325022035
[[0.38702128 0.83276386 0.84223977 0.9300234 ]]
0.22916657301068205
[[0.07051506 0.96605835 0.96731682 0.99227647]]
0.03715960745981244
[[0.0325645  0.98433019 0.98471079 0.99665022]]
0.016915776418660163
[[0.02044062 0.99019278 0.99037287 0.99792867]]
0.010563823603022169
[[0.01469857 0.99296657 0.99307177 0.99851586]]
0.007575882303454407
[[0.01139942 0.99455771 0.99462697 0.99884861]]
0.005865405135399684
[[0.00927416 0.99558104 0.99563028 0.99906149]]
0.004766106220478539
[[0.00779767 0.99629092 0.99632784 0.99920888]]
0.0040036401644313446
[[0.00671546 0.99681052 0.99683931 0.99931674]]
0.0034454688604593146
